"""empty message

Revision ID: 59fe8696f267
Revises: 9ef3dd615fa6
Create Date: 2022-12-11 11:10:34.356995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59fe8696f267'
down_revision = '9ef3dd615fa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.String(length=180), nullable=False),
    sa.Column('recipe_url', sa.String(length=250), nullable=False),
    sa.Column('recipe_title', sa.String(length=250), nullable=False),
    sa.Column('category_name', sa.String(length=180), nullable=True),
    sa.Column('recipe_img', sa.String(length=10000), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopping_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipeLabel', sa.String(length=180), nullable=True),
    sa.Column('ingredientIndex', sa.String(length=20), nullable=True),
    sa.Column('ingredientText', sa.String(length=180), nullable=True),
    sa.Column('recipeUri', sa.String(length=300), nullable=True),
    sa.Column('quantity', sa.String(length=20), nullable=True),
    sa.Column('food', sa.String(length=180), nullable=True),
    sa.Column('isChecked', sa.Boolean(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('measure', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hashed', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=True))
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('password')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('name')
        batch_op.drop_column('username')
        batch_op.drop_column('password_hashed')

    op.drop_table('shopping_list')
    op.drop_table('favorite')
    op.drop_table('category')
    # ### end Alembic commands ###
